#include <cstdio>
#include <cstdlib>
#include <vector>
#include <random>
#include <algorithm>
#include <limits>
#include <cuda_runtime.h>

// #define PROFILE

#define TASK_SPAWN_CUTOFF 128

#include "task_api_all.cuh"

struct Task {
    int left;
    int right;
};

// Global device pointers to data and buffer
__device__ int* g_data;
__device__ int* g_buf;

// Merge [left..mid] and [mid+1..right] from g_data into g_buf, then copy back
__device__ __forceinline__ void merge_device(int* a, int* buf, int left, int mid, int right) {
    int i = left, j = mid + 1, k = left;
    while (i <= mid && j <= right) {
        if (a[i] <= a[j]) buf[k++] = a[i++];
        else               buf[k++] = a[j++];
    }
    while (i <= mid)  buf[k++] = a[i++];
    while (j <= right) buf[k++] = a[j++];
    for (int t = left; t <= right; ++t) a[t] = buf[t];
}

__device__ __forceinline__ void mergesort_rec_device(int* a, int left, int right) {
    if (left >= right) return;
    int mid = left + ((right - left) >> 1);
    mergesort_rec_device(a, left, mid);
    mergesort_rec_device(a, mid + 1, right);
    merge_device(a, g_buf, left, mid, right);
    return;
}

// Task function: mergesort
TASK_DEF(mergesort_task, Task) {
    int left, right, n, mid;
    TASK_BEGIN();

    left = self->left;
    right = self->right;
    n = right - left + 1;
    
    // Base case: single element or empty range
    if (left >= right) {
        TASK_FINISH();
    }
    
    if (n > TASK_SPAWN_CUTOFF) { 
        mid = left + ((right - left) >> 1);
        Task lchild; lchild.left = left;      lchild.right = mid;
        Task rchild; rchild.left = mid + 1;   rchild.right = right;
        TASK_SPAWN(lchild, mergesort_task, 0);
        TASK_SPAWN(rchild, mergesort_task, 0);
        TASK_JOIN(0);
    } else {
        mergesort_rec_device(g_data, left, right);
        TASK_FINISH();
    }

    // Recompute indices after resume
    left = self->left; right = self->right; mid = left + ((right - left) >> 1);
    merge_device(g_data, g_buf, left, mid, right);
    TASK_FINISH();
    TASK_END();
}

// Enqueue initial task (left=0, right=n-1)
__global__ void enqueue_initial_task(int n) {
    Task initial = {0, n - 1};
    TASK_ENQUEUE_INITIAL(Task, mergesort_task, initial);
}

// Helpers to bind device pointers
static inline cudaError_t bind_device_arrays(int* d_data, int* d_buf) {
    cudaError_t st;
    st = cudaMemcpyToSymbol(g_data, &d_data, sizeof(d_data)); if (st != cudaSuccess) return st;
    st = cudaMemcpyToSymbol(g_buf,  &d_buf,  sizeof(d_buf));  if (st != cudaSuccess) return st;
    return cudaSuccess;
}

// Load array from binary file
std::vector<int> load_array(const char* filename, size_t& n) {
    std::vector<int> data;
    FILE* fp = fopen(filename, "rb");
    if (!fp) {
        fprintf(stderr, "Error: Cannot open %s for reading\n", filename);
        return data;
    }
    
    // Read size
    if (fread(&n, sizeof(size_t), 1, fp) != 1) {
        fprintf(stderr, "Error: Cannot read size from %s\n", filename);
        fclose(fp);
        return data;
    }
    
    // Allocate and read data
    data.resize(n);
    if (fread(data.data(), sizeof(int), n, fp) != n) {
        fprintf(stderr, "Error: Cannot read data from %s\n", filename);
        data.clear();
        fclose(fp);
        return data;
    }
    
    fclose(fp);
    printf("Loaded %zu elements from %s\n", n, filename);
    return data;
}

int main(int argc, char** argv) {
    if (argc < 2) {
        printf("Usage: %s <data_file> [reference_file]\n", argv[0]);
        printf("  data_file: Binary file containing array data (generated by gen_vector)\n");
        printf("  reference_file: Optional reference file for verification\n");
        return 1;
    }
    
    const char* data_file = argv[1];
    const char* reference_file = (argc > 2) ? argv[2] : nullptr;
    
    cudaSetDevice(0);
    cudaError_t st = init_task_runtime<Task>();
    if (st != cudaSuccess) {
        fprintf(stderr, "init_task_runtime failed: %s\n", cudaGetErrorString(st));
        return 1;
    }

    // Load data from file
    size_t N;
    std::vector<int> h = load_array(data_file, N);
    if (h.empty()) {
        return 1;
    }
    
    // Create reference for verification
    std::vector<int> gold;
    if (reference_file) {
        size_t ref_n;
        gold = load_array(reference_file, ref_n);
        if (gold.empty() || ref_n != N) {
            fprintf(stderr, "Error: Reference file size mismatch\n");
            return 1;
        }
    } else {
        gold = h;
        std::sort(gold.begin(), gold.end());
    }

    // Device buffers
    int* d_data = nullptr; int* d_buf = nullptr;
    cudaMalloc(&d_data, sizeof(int) * N);
    cudaMalloc(&d_buf,  sizeof(int) * N);
    cudaMemcpy(d_data, h.data(), sizeof(int) * N, cudaMemcpyHostToDevice);
    bind_device_arrays(d_data, d_buf);

    // Run
    cudaEvent_t start, stop;
    cudaEventCreate(&start);
    cudaEventCreate(&stop);
    cudaEventRecord(start);

    enqueue_initial_task<<<1, 1>>>(static_cast<int>(N));
    execute_task_loop<TERMINATE_ON_FIRST_TASK_FINISH, Task><<<NUM_BLOCKS, THREADS_PER_BLK>>>();

    cudaEventRecord(stop);
    cudaEventSynchronize(stop);
    float ms = 0.f;
    cudaEventElapsedTime(&ms, start, stop);

    // Copy back and verify
    cudaMemcpy(h.data(), d_data, sizeof(int) * N, cudaMemcpyDeviceToHost);
    std::sort(gold.begin(), gold.end());
    bool ok = std::is_sorted(h.begin(), h.end()) && (h == gold);

    // Match fib.cu output style (+ Correct)
    printf("Mergesort(%zu) = %s\n", N, ok ? "Correct" : "Incorrect");
    printf("Kernel execution time: %.3f ms (%.6f s)\n", ms, ms / 1000.0);

    #ifdef PROFILE
    visualize_profile("mergesort");
    #endif

    cudaFree(d_data); cudaFree(d_buf);
    return ok ? 0 : 1;
}
